freinds=('Gita','Sita','Ram')
print(freinds)
new=list(freinds)
new.append('Nita')
new.append('Shyam')
new.remove('Gita')
freinds=tuple(new)
print ("I have "+str(len(freinds))+" friends")
print(freinds)